-- Migration: 0001_memories.sql
-- Purpose: create the `memories` table — the core object of the personal memory graph app.
-- Each row is a free-text memory/story belonging to a user, optionally embedded via Voyage AI
-- for similarity search. `embedding` starts NULL and is populated asynchronously by the
-- backend after insert.
--
-- Idempotent: safe to re-run (guards on extension/table/index creation, drop-then-create for
-- policies since Postgres has no `create policy if not exists`).
--
-- ROLLBACK (manual — Supabase migrations in this project are forward-only files, no separate
-- down-migration mechanism, so the rollback path is documented here instead):
--   drop policy if exists "memories_select_own" on public.memories;
--   drop policy if exists "memories_insert_own" on public.memories;
--   drop policy if exists "memories_update_own" on public.memories;
--   drop policy if exists "memories_delete_own" on public.memories;
--   drop index if exists public.memories_embedding_hnsw_idx;
--   drop table if exists public.memories;
--   -- Not dropping the `vector` extension here: other tables/migrations may come to depend
--   -- on it. If this table is truly the only consumer, also run:
--   --   drop extension if exists vector;

-- pgvector extension (fresh project — not yet enabled).
create extension if not exists vector;

create table if not exists public.memories (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  text text not null,
  embedding vector(1024),
  created_at timestamptz not null default now()
);

-- Row Level Security: every row is scoped to its owning user, no exceptions.
alter table public.memories enable row level security;

drop policy if exists "memories_select_own" on public.memories;
create policy "memories_select_own"
  on public.memories
  for select
  using (auth.uid() = user_id);

drop policy if exists "memories_insert_own" on public.memories;
create policy "memories_insert_own"
  on public.memories
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "memories_update_own" on public.memories;
create policy "memories_update_own"
  on public.memories
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "memories_delete_own" on public.memories;
create policy "memories_delete_own"
  on public.memories
  for delete
  using (auth.uid() = user_id);

-- Similarity-search index on `embedding`.
--
-- The table starts empty, so this isn't urgent yet — but we add it now rather than defer it.
-- We use HNSW rather than IVFFlat specifically because IVFFlat's list-based clusters are
-- trained from existing rows at index-build time: building it against an empty table (or a
-- near-empty one) produces poor clustering and would need a manual REINDEX once real data
-- lands. HNSW builds an incremental graph with no such training step, so it stays useful as
-- rows trickle in from day one. The tradeoff is higher build/maintenance cost per insert,
-- which is acceptable at this stage given expected write volume. Distance operator is cosine
-- (vector_cosine_ops), matching how Voyage AI embeddings are typically compared. Rows with a
-- NULL embedding (not yet generated by the backend) are simply excluded from the index.
create index if not exists memories_embedding_hnsw_idx
  on public.memories
  using hnsw (embedding vector_cosine_ops);
